repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --safe
        language: system
        types: [python]
        files: ^src/.*\.py$

      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        files: ^src/.*\.py$

      - id: ruff
        name: ruff
        entry: poetry run ruff check --fix
        language: system
        types: [python]
        files: ^src/.*\.py$

      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        files: ^src/.*\.py$ 